### ISSUE TITLE
Metadata.json device key required

### ISSUE THREAD

**Issue by gorkemgoknar** [nebuly-ai/nebullvm#106]
0.5.0 version breaks loading onnx models created at 0.4.4 version
adding a  "device": "GPU" works to metadata.json, but it should just load as is if not available.

```

---------------------------------------------------------------------------
---> 51 optimized_decoder = PytorchONNXInferenceLearner.load(Path(file_path, "optimized_decoder"))
     52 return DecoderOptimizedInference(optimized_decoder)

File ~/myenv/lib/python3.8/site-packages/nebullvm/inference_learners/onnx.py:175, in ONNXInferenceLearner.load(cls, path, **kwargs)
    173 metadata = LearnerMetadata.read(path)
    174 input_tfms = metadata.input_tfms
--> 175 device = metadata.device
    176 if input_tfms is not None:
    177     input_tfms = MultiStageTransformation.from_dict(
    178         metadata.input_tfms
    179     )

AttributeError: 'LearnerMetadata' object has no attribute 'device'
```

**Comment by valeriosofi** [comment]
Hello @gorkemgoknar, thanks! Yep with the latest version we had to add the device variable to the inference learner, in order to allow the user to choose the inference device to be used. For now you can use the easy fix you proposed (manually adding the key in the json of your old model), but we will fix this issue in the next release!
