### ISSUE TITLE
Can one optimized model deploy to multiple device using speedter?

### ISSUE THREAD

**Issue by hardikdava** [nebuly-ai/nebullvm#149]
Hello @nebuly-ai , I have a question regarding model deployment. If I have saved an optimzed model generated by Speedster on first machine and later can I deploy the same optimized model to other machines as well?

**Comment by valeriosofi** [comment]
Hello @hardikdava, It is usually recommended to optimise the model on the same machine on which you then want to use it, because the type of optimisation and the techniques selected by speedster to optimise the model depend heavily on the type of hardware (especially cpu and gpu). So if you optimise a model on one machine, it is not guaranteed that that model will be the optimal one on the other machines. If, on the other hand, you have several machines with the same hardware (same gpu/cpu), you can optimise it on one, save it and transfer it to the others.

**Comment by hardikdava** [comment]
Thank for your reply. I understand it properly. @valeriosofi
