### ISSUE TITLE
[Chatllama] Is the training correct?

### ISSUE THREAD

**Issue by menandro** [nebuly-ai/nebullvm#268]
llama_model.generate returns (llama_model.py, line 545):
`generated_tokens.append(next_token)`
and saved to `sequences` called by (actor.py, line 210).

Above generates `max_length` tokens which is set in (actor.py, line 208):
`max_length = states.shape[1] + max_completion`
Above code takes the length of the input tokens (states) and max_completion. But, line 216 we have:
`actions = sequences[:, states.shape[1] :]  # noqa E203`
which means `actions` is taken as the last `max_collection` tokens of sequences. 

Shouldn't actions be the entire `generated_tokens` and `sequences` should be `states + " " + generated_tokens`?

**Comment by sallywang147** [comment]
following this thread - that might cause critical errors. Hopefully we get a response soon

**Comment by PierpaoloSorbellini** [comment]
Hi @menandro Yes you are right, the mistake was made because when porting to HF we also used the generate of HF and it also returns the input sequence while in llama_model.py the generate only returns the completion. 
We will fix it as soon as possible and test for consistency. 
Thanks for pointing this out.
