### ISSUE TITLE
`import nebullvm` is slow

### ISSUE THREAD

**Issue by shiyu22** [nebuly-ai/nebullvm#81]
As shown in the figure below, `import nebullvm` takes 6.8 seconds but loading the model only takes 1.5 seconds. Why is import so slow? 
<img width="734" alt="截屏2022-07-25 18 18 46" src="https://user-images.githubusercontent.com/53459423/180773170-418c3736-1734-4455-91bf-57f25d1e4996.png">

**Comment by valeriosofi** [comment]
Hi @shiyu22, the import is a bit slow because internally it imports all the required libraries (pytorch, tensorflow etc.), so I'm not surprised that loading the model is faster. Of course on a jupyter notebook you don't have to import again nebullvm each time you load or optimize a model, you can import it only once.

**Comment by shiyu22** [comment]
@valeriosofi Thanks for your answer, I tried `import tensorflow` and `import tvm` will take 2-3s, but my program is only related to tensor, is it possible not to import tensorflow and tvm, what do you think?

What I want to say is that because import nebullvm is too slow, is it possible to customize the use of torch or tensorflow according to user environment?

**Comment by valeriosofi** [comment]
We can consider to add this feature in future, but for now it's not possible. If you want to contribute you can make a PR, we would be more than happy for your contribution ;)
